<?php
return [
    'adminEmail'=>'natkay.robert@nrcode.com',
    'isPartOfWline' => true,
    'maxtime'=>1800, //30min
    'cacheDuration'=>3600,
    'waters_version'=>3,
    'visited_version'=>3,
    'missions_version'=>3,
    'baits_version'=>1,
    'items_version'=>1,
    'parts_version'=>1,
    'parts_version'=>1,
    'listPerPage'=>10,
    'shopItemsPerPage'=>4,
    'wlineHost'=>'http://wline.hu/',
    'packagesSms' => [],
    'cronPassword' => 'secret',
    'wlineUsersTable' => 'users',
    'wlineRefreshAttribute' => 'lastRefresh',
    'googleMapsApiKey' => '',
    //game mechanic attributes
    'goldPerGateMission' => 5,
    'setPartFindTimeLimit' => 86400,
    'setPartFindXpLimit' => 100,
    'setPartFindChanceInitial' => 5,
    'setPartFindChanceTimeLimit' => 2,
    'setPartFindChanceXpLimit' => 1,
    'mapCenterCoords' => '45.807504,17.82389',
    'duelLevelRequirement' => 20,
    'duelWeakerOpponentLevelDiff' => 5,
    'duelMaxCallPerHour' => 3,
    'duelRevengeTimeLimitHours' => 12,
    'competitorCompensatorMin' => 33,
    'competitorCompensatorMax' => 66,
    'clubJoinLevelRequirement' => 30,
    'clubMaxMembers' => 8,
    'clubCreateLevelRequirement' => 45,
];
